### PR TITLE
Adds empty Rich Text Document file

### PR DESCRIPTION
**Pull request by PatrickAuld**
Empty RTF file created on Mac using TextEdit.

### CODE REVIEW

**Comment by 13rac1** [comment]
Awesome! Just one?! :smiling_imp: Gotta collect them all! 

I've got a `text-helloworld.rtf` made in libreoffice already created, but not pushed. Adding all actually empty is good too.

**Comment by 13rac1** [comment]
Empty is too small for a simple text format like this:
```
byte count: 154
image size: 13x13
primary hue from hash: 255.53
padding bytes: 15
padded byte count: 169
calculating...
writing...
Done.
```

Needs more data! I've checked my `Helloworld.rtf` Ends up with lots of boilerplate garbage, but it's just text.

text-empty rtf600

This makes me realize I need to see if I can get CI setup to automatically render the first few images.

**Comment by PatrickAuld** [comment]
Getting the CI to render things would be great; I don't have rust setup yet so I haven't actually tried to even compile things yet. Just adding files :)

**Comment by 13rac1** [comment]
Haven't installed Rust?!?! I don't like this "run this script off the website", but there's no current `deb` files. 
```
$ curl https://sh.rustup.rs -sSf | sh
```

I would cross compile MacOS and Windows binaries if this were Go, but [it's not an option in Rust](https://github.com/japaric/rust-cross#i-want-to-build-binaries-for-linux-mac-and-windows-how-do-i-cross-compile-from-linux-to-mac).

**Comment by 13rac1** [comment]
Alrighty. CircleCI is running the build on all pushes and deploys to gh-pages after pushes master: https://github.com/eosrei/file-vis/blob/c478b4cb3a7fa63487524a950b5b7eb169721b68/circle.yml The images are actually on Circle now. Need to create a way to get them into these PR comments efficiently.

In the meantime, this text file is super simple. Can you find something more complex? :D

**Pull request closed without merging**
